---
# tasks file for addwebserver
- name: Create docker directory
  file:
    path: docker
    state: directory

- name: Copy from docker dir files to remote
  copy:
    src: docker/web/
    dest: docker/web/
    
- name: Build web server using Docker image
  docker_image:
    name: "{{ web_docker_img_name }}"
    build:
      path: "{{ web_dockerfile_path }}"
      pull: no
    state: present
    source: build
  register: web_docker_img
  
- name: Restart docker
  service:
    name: docker
    state: restarted

- name: Clear iptables routing filter
  shell: iptables -F; iptables -X
  when: web_docker_img.changed
  
- name: Run Web server container
  docker_container:  
    name: "{{ web_container_name }}"
    image: "{{ web_docker_img_name }}:{{ web_docker_img_tag }}"
    state: started
    ports: "{{ web_ports }}"


